"""Port MySQL → Postgres/Neon (DDL, RETURNING, upserts, datas). Sem banco live."""
import sys
import unittest
from datetime import datetime
from pathlib import Path
from unittest.mock import MagicMock, patch

BACKEND_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_DIR))

from routes import database as db


class DdlTranslatorTest(unittest.TestCase):
    DDL = """CREATE TABLE IF NOT EXISTS t (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        foto MEDIUMTEXT NULL,
        lida TINYINT(1) DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY uq_x (user_id),
        INDEX idx_x (user_id),
        INDEX idx_y (created_at),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )"""

    def test_translate(self):
        table_sql, indexes = db.translate_ddl_to_pg(self.DDL)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", table_sql)
        self.assertNotIn("AUTO_INCREMENT", table_sql)
        self.assertNotIn("MEDIUMTEXT", table_sql)
        self.assertNotIn("TINYINT", table_sql)
        self.assertIn("SMALLINT", table_sql)
        self.assertNotIn("DATETIME", table_sql)
        self.assertNotIn("ON UPDATE", table_sql)
        self.assertNotIn("INDEX", table_sql)
        self.assertIn("UNIQUE (user_id)", table_sql)
        self.assertIn("TIMESTAMP DEFAULT CURRENT_TIMESTAMP", table_sql)
        self.assertEqual(len(indexes), 2)
        self.assertTrue(all("CREATE INDEX IF NOT EXISTS" in i for i in indexes))
        self.assertTrue(any("idx_x" in i and "ON t (user_id)" in i for i in indexes))

    def test_add_column_dtype(self):
        self.assertEqual(db._pg_dtype("DATETIME NULL"), "TIMESTAMP NULL")
        self.assertEqual(db._pg_dtype("MEDIUMTEXT NULL"), "TEXT NULL")
        self.assertEqual(db._pg_dtype("VARCHAR(50) NULL"), "VARCHAR(50) NULL")

    def test_month_start_sql(self):
        with patch.object(db, "DB_ENGINE", "postgres"):
            self.assertIn("date_trunc", db.month_start_sql())
        with patch.object(db, "DB_ENGINE", "mysql"):
            self.assertIn("DATE_FORMAT", db.month_start_sql())


class InsertGetIdTest(unittest.TestCase):
    def test_mysql_lastrowid(self):
        cur = MagicMock()
        cur.lastrowid = 42
        with patch.object(db, "DB_ENGINE", "mysql"):
            self.assertEqual(db.insert_get_id(cur, "INSERT INTO t (a) VALUES (%s)", (1,)), 42)
        cur.execute.assert_called_once_with("INSERT INTO t (a) VALUES (%s)", (1,))

    def test_postgres_returning(self):
        cur = MagicMock()
        cur.fetchone.return_value = {"id": 7}
        with patch.object(db, "DB_ENGINE", "postgres"):
            got = db.insert_get_id(cur, "INSERT INTO t (a) VALUES (%s);", (1,))
        self.assertEqual(got, 7)
        sql = cur.execute.call_args.args[0]
        self.assertIn("RETURNING id", sql)
        self.assertNotIn(";;", sql)


class PaymentMonthsTest(unittest.TestCase):
    def test_add_months(self):
        from routes.payment import _add_months
        self.assertEqual(_add_months(datetime(2026, 1, 31), 1), datetime(2026, 2, 28))
        self.assertEqual(_add_months(datetime(2026, 11, 15), 3), datetime(2027, 2, 15))
        self.assertEqual(_add_months(datetime(2026, 5, 10), 0), datetime(2026, 5, 10))


class EventUpsertTest(unittest.TestCase):
    def test_selector(self):
        from services.automotive_events import _event_upsert_sql
        with patch("routes.database.DB_ENGINE", "postgres"):
            # is_postgres() lê o global do módulo routes.database
            import routes.database as d
            with patch.object(d, "DB_ENGINE", "postgres"):
                self.assertIn("ON CONFLICT (id)", _event_upsert_sql())
            with patch.object(d, "DB_ENGINE", "mysql"):
                self.assertIn("ON DUPLICATE KEY", _event_upsert_sql())


if __name__ == "__main__":
    unittest.main()
